/** Long-form project write-ups for featured cards (click to expand). */
export const featuredProjectDetails = {
  nachosOs: [
    {
      type: 'paragraph',
      text: 'Implemented timer-driven thread sleeping, thread joining, interrupt-based condition variables, and cancellable timed waits; coordinated blocking and wakeups through atomic state updates without busy-waiting.',
    },
    {
      type: 'list',
      items: [
        'Built tagged rendezvous for pairwise value exchange and asynchronous futures supporting multiple result consumers, using locks and condition variables to synchronize concurrent threads.',
        'Enabled multiprogramming through six file system calls and exec, join, and exit; implemented per-process file descriptor tables, unique process IDs, parent–child lifecycle tracking, page-table address translation, synchronized noncontiguous physical page allocation, read-only protection, argument validation, and resource reclamation.',
        'Implemented demand paging with lazy frame allocation, page fault handling, clock/second-chance replacement, an inverted page table, and reusable swap slots; reduced redundant disk writes using dirty bits and protected concurrent I/O and user–kernel memory transfers through page pinning and condition-based waiting.',
      ],
    },
  ],
  dayGenie: [
    {
      type: 'paragraph',
      text:
        'The inspiration for our auto-scheduling project emerged from the increased need for automated and personalized recommendations in travel planning tools. We recognized that multi-agent LLMs hold immense potential to tackle complex tasks such as personalized scheduling. This potential drove our team to want to explore how these models could offer solutions that can integrate into daily life problems. We were also inspired to create this app because of the tediousness of scheduling, and we recognized that our tool could save lots of time.',
    },
    { type: 'heading', text: 'Our Goal' },
    {
      type: 'paragraph',
      text:
        'We aim to simplify the process of planning trips and transport for important trips. We also want to introduce users to popular and fun locations along the way. DayGenie automatically generates recommendations based on user preferences and user schedule.',
    },
    { type: 'heading', text: 'How we built it (Structure of our model)' },
    { type: 'subheading', text: 'Agent Workflow' },
    {
      type: 'paragraph',
      text:
        'DayGenie is constructed as a decentralized multi-agent large language model. We defined 5 LLM Agents (InfoAgent, MapAgent, RedditAgent, SummaryAgent, Feedback Agent), each with specific prompting for their purpose.',
    },
    {
      type: 'list',
      items: [
        'User Input: user preference (str), Google Calendar schedule (Google Calendar API call)',
        'InfoAgent: Fetches user input, generates prompts for MapAgent and RedditAgent.',
        'MapAgent: Finds the location of events happening in the calendar.',
        'RedditAgent: Calls Reddit API, fetches and analyzes reviews based on important keyword input.',
        'SummaryAgent: Calculates transportation (time, cost) and recommendations based on locations and preferences.',
        'FeedbackAgent: Gets physical feedback from the user; if negative, run model again — else output is provided to the user.',
        'Model Output: A list of personalized recommendations for transportation, restaurant/cafe, and event places.',
      ],
    },
    { type: 'subheading', text: 'Conversation construction' },
    {
      type: 'paragraph',
      text:
        'We used Fetch AI to facilitate conversations and communication between our agents. We designed each agent to solve their own specific tasks and then pass results onto others in our workflow.',
    },
    { type: 'subheading', text: 'Website construction' },
    {
      type: 'paragraph',
      text:
        'Our website is constructed using Next.js and Tailwind CSS. We built an intuitive and attractive user interface using these tools. While we have not deployed the website yet, we plan on doing so in the future.',
    },
    { type: 'heading', text: 'Challenges we ran into' },
    {
      type: 'list',
      items: [
        'Number of Agents: How many agents should we define?',
        'Reducing hallucinations of agents: How do we handle hallucinations generated by large language models?',
        'Understanding Fetch AI: We had some issues understanding the structure of Fetch AI and how to use it most effectively.',
      ],
    },
    { type: 'heading', text: 'Accomplishments' },
    {
      type: 'paragraph',
      text:
        'During this hackathon, the major accomplishment was successfully generating conversations between the agents we designed. By calling Google Calendar API, user input, Google Map API, and Reddit API, we could successfully generate output recommendations for users.',
    },
    {
      type: 'paragraph',
      text:
        'Towards the end of the project, we were also able to add a feedback agent, which plays a crucial role in ensuring that users receive the exact information they are seeking from our application.',
    },
    {
      type: 'paragraph',
      text:
        'Finally, our team cooperation made all of this possible — we learned a lot from each other and had fun participating in this project.',
    },
  ],
  autismAsd: [
    {
      type: 'paragraph',
      text:
        'Autism Spectrum Disorder (ASD) is a neural disorder caused by incomplete development in the central nervous system. Standard diagnosis often relies on long surveys. We study Instagram behavior of adolescents and young adults using text, images, and behavioral signals to estimate ASD tendency (Yes/No). Best model F1 ≈ 82%.',
    },
    { type: 'heading', text: 'Task description' },
    {
      type: 'paragraph',
      text:
        'For p users with n posts each, we extract text, image, and behavioral features per user. Post-level sets: TEXT_ui = {text_ui1,…,text_uin}, IMAGE_ui = {image_ui1, image_ui2, image_ui3}, and BEHAVIOR_ui = {b_ui1,…,b_uin}. The model predicts whether a user is likely to have ASD.',
    },
    { type: 'heading', text: 'Methods — data collection (Instagram)' },
    {
      type: 'list',
      items: [
        'Languages: Chinese, English, Japanese. Exclude unofficial/commercial accounts and profiles mentioning other mental illnesses (e.g. bipolar, depression) that could confound behavior.',
        'Users with fewer than 3,000 followers.',
        'Crawler loads each profile page; latest 20 posts — first photo, caption text, likes, follower count.',
      ],
    },
    { type: 'subheading', text: 'Image pipeline' },
    {
      type: 'paragraph',
      text:
        'Two signals form a 3-D image vector: (1) YOLO-based object detection — human area vs. total image area, averaged over 20 posts (autism-related work often shows more object- vs. people-focused photos). (2) Similarity across the 20 images via a similarity model. Research motivation: repetitive interest-focused posting and different photo subjects vs. typical users.',
    },
    { type: 'heading', text: 'Text features' },
    {
      type: 'paragraph',
      text:
        'Word2Vec captures semantic/syntactic context. All words from 20 posts are mapped to vectors V(i,m,j); user text is summarized as a fixed-length representation (20-D feature vector after concatenation/padding strategy in the pipeline).',
    },
    {
      type: 'list',
      items: [
        'Preprocessing: remove links/punctuation; extract hashtags; count emoticons. Chinese: CKIP; English: Apache Word Segment; Japanese: MeCab.',
        'Word2Vec: 300×1 vectors per word; similar words → closer vectors. Variable post length → pad to max length with zeros.',
      ],
    },
    { type: 'heading', text: 'Image features (YOLO & similarity)' },
    {
      type: 'paragraph',
      text:
        'YOLOv5 (vs YOLOv3) for multi-object detection and person-area ratio. For similarity: classify photographed vs. drawn images; photographed paths use transfer learning on Torchvision ResNet50 with a Siamese network (anchor/positive/negative triplets, 128-D embeddings, cosine/Euclidean distance). Training set: 123 celebrity/held-out photos plus nine ASD-labeled accounts excluded from the final classifier set. Average pairwise similarity per user feeds the image branch.',
    },
    { type: 'heading', text: 'Behavior features' },
    {
      type: 'paragraph',
      text:
        'Social: posting frequency, likes, followers, following. Writing: total words, first-person count, autism-related hashtags (#autism #autistic #autismawareness #autismacceptance #asd #adhd), total hashtags, emoji count, recurring words. Min–max normalization to [0,1]. Example group means (TD vs ASD): words 1214.8 vs 5364.3; autism hashtags 0 vs 32.0; posting frequency (3 mo) 4.25 vs 35.1; likes 83.7 vs 260.8; followers 794.5 vs 626.3; following 1045.5 vs 2205.6.',
    },
    { type: 'heading', text: 'Prediction model' },
    {
      type: 'paragraph',
      text:
        'Three feature types: image (3-D: YOLO person share, photo similarity, drawing similarity), behavior (10-D, Table I), text (300-D per word → Flatten → Dense 128 ReLU). Image + behavior pass through Dense(64); branches concatenate (64 + 128) then feed a CNN classifier.',
    },
    {
      type: 'list',
      items: [
        'SMOTE to balance classes before training.',
        'CNN: three conv layers (5×1 max pooling, ReLU), two fully connected layers; Softmax output; label 1 if probability > 0.5.',
        'L2 regularization against overfitting; Adam optimizer with categorical cross-entropy loss.',
      ],
    },
    { type: 'heading', text: 'Results' },
    {
      type: 'paragraph',
      text:
        'Best F1 score ≈ 82%. The study shows multimodal social-media signals (text, image, behavior) can support ML-based screening insights for autistic tendency in young adults on Instagram.',
    },
  ],
}
